/* Lotus Spa (Beauty & Wellness) · TRANG MẪU (chưa phải trang chính thức của spa).
 * Giá: lotusspaphuquoc.com /massage-therapy, /foot-treatment, /package (09/10/2026). 7 ngôn ngữ: en vi ja ko fr zh ru. */
(function(){
function L(en,vi,ja,ko,fr,zh,ru){ return {en:en,vi:vi,ja:ja,ko:ko,fr:fr,zh:zh,ru:ru}; }
var FREE = L("Free pick-up & drop-off","Đưa đón miễn phí","無料送迎","무료 픽업·드롭","Navette gratuite aller-retour","免费接送","Бесплатный трансфер");
window.SITE_CONFIG = {
  slug: "lotus-spa", kind: "spa", mark: "lotus",
  name: "Lotus Spa", shortName: "Lotus Spa",
  langs: ["en","vi","ja","ko","fr","zh","ru"], fallbackLang: "en",
  refPrefix: "LT",
  heroTitle: L("Lotus Spa<br><em>Beauty &amp; Wellness</em>","Lotus Spa<br><em>Beauty &amp; Wellness</em>","Lotus Spa<br><em>Beauty &amp; Wellness</em>","Lotus Spa<br><em>Beauty &amp; Wellness</em>","Lotus Spa<br><em>Beauty &amp; Wellness</em>","Lotus Spa<br><em>Beauty &amp; Wellness</em>","Lotus Spa<br><em>Beauty &amp; Wellness</em>"),
  eyebrow: L("Since 2016 · Phu Quoc","Từ 2016 · Phú Quốc","2016年創業 · フーコック","Since 2016 · 푸꾸옥","Depuis 2016 · Phu Quoc","始于 2016 · 富国岛","С 2016 года · Фукуок"),
  tagline: L(
    "Let your body relax in a worthy place — three spas on Phu Quoc, one booking page.",
    "Hãy đến một nơi xứng đáng với bạn — ba cơ sở trên đảo Phú Quốc, đặt lịch chung một trang.",
    "心と体をゆだねるにふさわしい場所へ。フーコック島に3店舗、ご予約はこのページから。",
    "몸과 마음을 맡기기에 걸맞은 곳. 푸꾸옥 세 지점을 한 페이지에서 예약하세요.",
    "Offrez à votre corps un lieu qui le mérite — trois spas à Phu Quoc, une seule page de réservation.",
    "让身心在值得的地方放松——富国岛三家分店，一页即可预约。",
    "Отдохните там, где вы этого достойны: три спа на Фукуоке — одна страница для записи."),
  heroImage: "assets/hero.webp", heroImageMobile: "assets/hero-m.webp", heroFocus: "50% 50%",
  about: {
    image: "assets/intro.webp",
    title: L("A worthy place to rest","Một nơi xứng đáng để nghỉ ngơi","ほっと一息つける場所","온전히 쉬어 갈 수 있는 곳","Un lieu digne de votre repos","值得停留的休憩之所","Место, достойное вашего отдыха"),
    text: L(
      "Since 2016, Lotus Spa has offered massage, skin care, nail and waxing treatments on Phu Quoc, now across three locations: Ong Lang, An Thoi and Tran Hung Dao in Duong Dong.\nTreatments range from Vietnamese traditional massage and hot stones to our Lotus herbal compress, with free pick-up and drop-off.",
      "Từ năm 2016, Lotus Spa mang đến massage, chăm sóc da, nail và waxing trên đảo Phú Quốc, nay có ba cơ sở: Ông Lang, An Thới và Trần Hưng Đạo (Dương Đông).\nLiệu trình từ massage truyền thống Việt Nam, đá nóng đến chườm thảo dược Lotus; có đưa đón miễn phí.",
      "2016年から、Lotus Spa はフーコック島でマッサージ、スキンケア、ネイル、ワックス脱毛をご提供しています。現在はオンラン、アントイ、ズオンドンのチャンフンダオ通りの3店舗です。\nベトナム伝統マッサージやホットストーンから、ロータス・ハーバルボールまで。無料送迎もございます。",
      "2016년부터 Lotus Spa는 푸꾸옥에서 마사지, 스킨케어, 네일, 왁싱을 선보여 왔으며, 현재 옹랑·안터이·즈엉동 쩐흥다오 세 지점을 운영합니다.\n베트남 전통 마사지와 핫스톤부터 로터스 허벌 볼 마사지까지, 무료 픽업·드롭 서비스도 제공합니다.",
      "Depuis 2016, Lotus Spa propose massages, soins de la peau, beauté des ongles et épilation à Phu Quoc, aujourd’hui dans trois adresses : Ong Lang, An Thoi et Tran Hung Dao à Duong Dong.\nDu massage traditionnel vietnamien aux pierres chaudes et au pochon d’herbes Lotus — navette gratuite aller-retour.",
      "自 2016 年起，Lotus Spa 在富国岛提供按摩、护肤、美甲和脱毛服务，现有三家分店：翁郎、安泰和阳东陈兴道路。\n从越南传统按摩、热石按摩到莲花草药球热敷，均提供免费接送。",
      "С 2016 года Lotus Spa предлагает на Фукуоке массаж, уход за кожей, маникюр и депиляцию — сейчас в трёх филиалах: Онг Ланг, Ан Тхой и на улице Чанхынгдао в Зыонгдонге.\nОт традиционного вьетнамского массажа и горячих камней до травяных мешочков Lotus; бесплатный трансфер в обе стороны."),
    signature: L("— Lotus Spa, since 2016","— Lotus Spa, từ 2016","— Lotus Spa（2016年創業）","— Lotus Spa, since 2016","— Lotus Spa, depuis 2016","— Lotus Spa，始于 2016","— Lotus Spa, с 2016 года")
  },
  highlights: [
    { icon:"pin", title:L("Three locations","Ba cơ sở","3つの店舗","세 지점","Trois adresses","三家分店","Три филиала"),
      text:L("Ong Lang, An Thoi and Duong Dong — choose the nearest one when you book.","Ông Lang, An Thới và Dương Đông — chọn cơ sở gần bạn ngay khi đặt lịch.","オンラン・アントイ・ズオンドン。ご予約時に近い店舗をお選びください。","옹랑·안터이·즈엉동. 예약할 때 가까운 지점을 선택하세요.","Ong Lang, An Thoi et Duong Dong — choisissez la plus proche en réservant.","翁郎、安泰、阳东——预约时选择离您最近的门店。","Онг Ланг, Ан Тхой и Зыонгдонг — выберите ближайший при записи.") },
    { icon:"car", title:FREE,
      text:L("Free transfer between your hotel and the spa.","Xe đưa đón miễn phí giữa khách sạn và spa.","ホテルとスパ間の送迎は無料です。","호텔과 스파 사이를 무료로 픽업·드롭해 드립니다.","Transfert gratuit entre votre hôtel et le spa.","酒店与水疗店之间免费接送。","Бесплатный трансфер между отелем и спа.") },
    { icon:"clock", title:L("Beauty O’clock","Beauty O’clock","ビューティー・オクロック","뷰티 어클락","Beauty O’clock","美丽时光","Beauty O’clock"),
      text:L("20% off every day from 9:00 to 11:00. Children aged 4–10 get 15% off.","Giảm 20% mỗi ngày từ 9:00 đến 11:00. Trẻ 4–10 tuổi giảm 15%.","毎日9:00〜11:00は20%オフ。4〜10歳のお子さまは15%オフ。","매일 9:00~11:00 20% 할인. 4~10세 어린이는 15% 할인.","−20 % chaque jour de 9 h à 11 h. Enfants de 4 à 10 ans : −15 %.","每天 9:00–11:00 享八折；4–10 岁儿童享 85 折。","Каждый день с 9:00 до 11:00 скидка 20%. Детям 4–10 лет — 15%.") }
  ],
  phone: "+84 988 992 001", phoneLink: "+84988992001",
  email: "lotusspa.river@gmail.com", website: "https://www.lotusspaphuquoc.com/",
  address: L("Lot 4, Ong Lang, Cua Duong, Phu Quoc","Lô 4, Ông Lang, Cửa Dương, Phú Quốc","フーコック、クアズオン、オンラン 4区画","푸꾸옥 끄어즈엉 옹랑 4구역","Lot 4, Ong Lang, Cua Duong, Phu Quoc","富国岛 Cửa Dương 翁郎 4 号地块","Участок 4, Онг Ланг, Кыа Зыонг, Фукуок"),
  branches: [
    { id:"ongl", name:L("Lotus Spa 1 · Ong Lang","Lotus Spa 1 · Ông Lang","Lotus Spa 1 · オンラン","Lotus Spa 1 · 옹랑","Lotus Spa 1 · Ong Lang","Lotus Spa 1 · 翁郎","Lotus Spa 1 · Онг Ланг"),
      short:L("Ong Lang, Cua Duong","Ông Lang, Cửa Dương","オンラン","옹랑","Ong Lang","翁郎","Онг Ланг"),
      address:L("Lot 4, Ong Lang, Cua Duong, Phu Quoc","Lô 4, Ông Lang, Cửa Dương, Phú Quốc","フーコック、クアズオン、オンラン 4区画","푸꾸옥 끄어즈엉 옹랑 4구역","Lot 4, Ong Lang, Cua Duong, Phu Quoc","富国岛 Cửa Dương 翁郎 4 号地块","Участок 4, Онг Ланг, Кыа Зыонг, Фукуок"),
      mapsLink:"https://www.google.com/maps/place/data=!4m2!3m1!1s0x31a78b18e0902079:0x489d56f85b6db517" },
    { id:"anthoi", name:L("Lotus Spa 2 · An Thoi","Lotus Spa 2 · An Thới","Lotus Spa 2 · アントイ","Lotus Spa 2 · 안터이","Lotus Spa 2 · An Thoi","Lotus Spa 2 · 安泰","Lotus Spa 2 · Ан Тхой"),
      short:L("Alley 469 Nguyen Van Cu","Hẻm 469 Nguyễn Văn Cừ","グエンヴァンクー通り 469番路地","응우옌반끄 469 골목","Ruelle 469 Nguyen Van Cu","阮文渠路 469 巷","переулок 469 Нгуен Ван Кы"),
      address:L("Alley 469 Nguyen Van Cu, An Thoi, Phu Quoc","Hẻm 469 Nguyễn Văn Cừ, An Thới, Phú Quốc","フーコック、アントイ、グエンヴァンクー通り 469番路地","푸꾸옥 안터이 응우옌반끄 469 골목","Ruelle 469 Nguyen Van Cu, An Thoi, Phu Quoc","富国岛安泰阮文渠路 469 巷","переулок 469 ул. Нгуен Ван Кы, Ан Тхой, Фукуок"),
      mapsLink:"https://www.google.com/maps/search/?api=1&query=Lotus+Spa+469+Nguyen+Van+Cu+An+Thoi+Phu+Quoc" },
    { id:"thd", name:L("Lotus Spa 3 · Duong Dong","Lotus Spa 3 · Dương Đông","Lotus Spa 3 · ズオンドン","Lotus Spa 3 · 즈엉동","Lotus Spa 3 · Duong Dong","Lotus Spa 3 · 阳东","Lotus Spa 3 · Зыонгдонг"),
      short:L("121/3 Tran Hung Dao","121/3 Trần Hưng Đạo","チャンフンダオ通り 121/3","쩐흥다오 121/3","121/3 Tran Hung Dao","陈兴道路 121/3","ул. Чанхынгдао, 121/3"),
      address:L("121/3 Tran Hung Dao, Duong Dong, Phu Quoc","121/3 Trần Hưng Đạo, Dương Đông, Phú Quốc","フーコック、ズオンドン、チャンフンダオ通り 121/3","푸꾸옥 즈엉동 쩐흥다오 121/3","121/3 Tran Hung Dao, Duong Dong, Phu Quoc","富国岛阳东陈兴道路 121/3","ул. Чанхынгдао, 121/3, Зыонгдонг, Фукуок"),
      mapsLink:"https://www.google.com/maps/search/?api=1&query=Lotus+Spa+121%2F3+Tran+Hung+Dao+Phu+Quoc" }
  ],
  mapsLink: "https://www.google.com/maps/place/data=!4m2!3m1!1s0x31a78b18e0902079:0x489d56f85b6db517",
  mapsEmbed: "https://maps.google.com/maps?q=Lotus%20Spa%20Ong%20Lang%20Phu%20Quoc&z=13&output=embed",
  reviewsLink: "https://www.google.com/maps/place/data=!4m2!3m1!1s0x31a78b18e0902079:0x489d56f85b6db517",
  hours: { open:"09:00", close:"22:00", days: L("Daily","Mỗi ngày","毎日","매일","Tous les jours","每天","Ежедневно") },
  slotMinutes: 30, lastBookingBeforeClose: 60, usdRate: 26300,
  categories: [
    { id:"body", name:L("Body massage","Massage body","ボディマッサージ","바디 마사지","Massages du corps","全身按摩","Массаж тела") },
    { id:"foot", name:L("Foot treatments","Chăm sóc chân","フットケア","풋 케어","Soins des pieds","足部护理","Уход за стопами") },
    { id:"pkg", name:L("Packages","Gói liệu trình","パッケージ","패키지","Forfaits","套餐","Пакеты"),
      note:L("Package prices already include the discount vs. booking each treatment separately.","Giá gói đã giảm so với đặt lẻ từng dịch vụ.","パッケージ料金は個別予約より割安です。","패키지 가격은 개별 예약보다 할인된 가격입니다.","Les forfaits sont déjà remisés par rapport aux soins à l’unité.","套餐价已比单项预约更优惠。","Цена пакета ниже, чем при записи на процедуры по отдельности.") }
  ],
  items: [
    { id:"trad", category:"body", image:"assets/c-trad.webp", variants:[{min:60,price:460000},{min:90,price:580000}],
      name:L("Vietnam Traditional","Massage truyền thống Việt Nam","ベトナム伝統マッサージ","베트남 전통 마사지","Massage traditionnel vietnamien","越南传统按摩","Традиционный вьетнамский массаж"),
      desc:L("Sunflower seed oil, acupressure and rhythmic strokes — back, arms, legs, finishing with a calming head massage.","Dầu hạt hướng dương, bấm huyệt và động tác nhịp nhàng — lưng, tay, chân, kết thúc bằng massage đầu thư giãn.","ひまわり油、指圧、リズミカルな手技で背中・腕・脚をほぐし、最後はヘッドマッサージで締めくくります。","해바라기씨 오일, 지압, 리드미컬한 손길로 등·팔·다리를 풀고 편안한 두피 마사지로 마무리합니다.","Huile de tournesol, acupression et gestes rythmés — dos, bras, jambes, puis un massage apaisant de la tête.","葵花籽油配合穴位按压与节奏手法，舒缓背部、手臂、腿部，最后以头部按摩收尾。","Масло семян подсолнечника, акупрессура и ритмичные движения — спина, руки, ноги и расслабляющий массаж головы.") },
    { id:"deep", category:"body", image:"assets/c-deep.webp", variants:[{min:60,price:510000},{min:90,price:650000}],
      name:L("Deep Tissue","Massage mô sâu (Deep Tissue)","ディープティシュー","딥티슈 마사지","Massage des tissus profonds","深层组织按摩","Глубокий массаж тканей"),
      desc:L("Firm, precise pressure for chronic tension in the back, neck and shoulders.","Lực ấn chắc, chính xác cho vùng lưng, cổ, vai căng cứng lâu ngày.","しっかりとした的確な圧で、背中・首・肩の慢性的なこりにアプローチ。","단단하고 정확한 압으로 등·목·어깨의 오래된 뭉침을 풀어 줍니다.","Pression ferme et précise pour les tensions chroniques du dos, de la nuque et des épaules.","力度扎实精准，针对背、颈、肩的长期紧绷。","Сильное точное давление при хроническом напряжении спины, шеи и плеч.") },
    { id:"stone", category:"body", image:"assets/c-stone.webp", variants:[{min:60,price:490000},{min:90,price:620000}],
      name:L("Hot Stone","Massage đá nóng","ホットストーン","핫스톤 마사지","Pierres chaudes","热石按摩","Массаж горячими камнями"),
      desc:L("Heated volcanic stones and gentle hands for deep relaxation.","Đá núi lửa làm ấm cùng đôi tay nhẹ nhàng, thư giãn sâu.","温めた溶岩石とやさしい手技で深いリラクゼーションへ。","따뜻한 화산석과 부드러운 손길로 깊은 휴식을.","Pierres volcaniques chauffées et mains douces pour une détente profonde.","温热火山石配合轻柔手法，深度放松。","Тёплые вулканические камни и мягкие руки — глубокое расслабление.") },
    { id:"thai", category:"body", card:false, variants:[{min:60,price:510000},{min:90,price:650000}],
      name:L("Thai","Massage Thái","タイ古式マッサージ","타이 마사지","Massage thaï","泰式按摩","Тайский массаж"),
      desc:L("No oil — acupressure and gentle stretching.","Không dầu — bấm huyệt và kéo giãn nhẹ.","オイルなし。指圧とやさしいストレッチ。","오일 없이 지압과 가벼운 스트레칭.","Sans huile — acupression et étirements doux.","无油，穴位按压加轻柔拉伸。","Без масла — акупрессура и мягкая растяжка.") },
    { id:"aroma", category:"body", card:false, variants:[{min:60,price:470000},{min:90,price:600000}],
      name:L("Aromatherapy","Massage tinh dầu","アロマセラピー","아로마테라피","Aromathérapie","芳香精油按摩","Ароматерапия"),
      desc:L("Light, soothing massage with your choice of essential oil.","Massage nhẹ nhàng với tinh dầu bạn chọn.","お好みの精油を使った、やさしいマッサージ。","원하는 에센셜 오일로 부드럽게.","Massage léger avec l’huile essentielle de votre choix.","自选精油，轻柔舒缓。","Лёгкий массаж с эфирным маслом на ваш выбор.") },
    { id:"swedish", category:"body", card:false, variants:[{min:60,price:490000},{min:90,price:620000}],
      name:L("Swedish","Massage Thụy Điển","スウェディッシュ","스웨디시 마사지","Massage suédois","瑞典式按摩","Шведский массаж"),
      desc:L("Medium pressure, varied strokes for full-body relaxation.","Lực vừa, nhiều kỹ thuật, thư giãn toàn thân.","ほどよい圧と多彩な手技で全身リラックス。","중간 강도의 다양한 손기술로 전신 이완.","Pression moyenne, gestes variés, détente du corps entier.","中等力度，多种手法，全身放松。","Средний нажим, разные техники, расслабление всего тела.") },
    { id:"herbal", category:"body", image:"assets/c-herbal.webp", variants:[{min:90,price:720000}],
      name:L("Lotus Herbal Compress","Chườm thảo dược Lotus","ロータス・ハーバルボール","로터스 허벌 볼 마사지","Pochons d’herbes Lotus","莲花草药球热敷","Травяные мешочки Lotus"),
      desc:L("Steamed herbal bags of ginger, turmeric, star anise and cinnamon.","Túi thảo dược hấp nóng: gừng, nghệ, hồi, quế.","生姜・ターメリック・八角・シナモンを蒸したハーブボール。","생강·강황·팔각·계피를 쪄 낸 허브 볼.","Pochons d’herbes chauds : gingembre, curcuma, anis étoilé, cannelle.","姜、姜黄、八角、肉桂蒸热的草药球。","Распаренные мешочки с имбирём, куркумой, бадьяном и корицей.") },
    { id:"head", category:"body", image:"assets/c-head.webp", variants:[{min:45,price:400000},{min:60,price:450000}],
      name:L("Head, Neck, Shoulder & Back","Đầu – cổ – vai – lưng","頭・首・肩・背中","두피·목·어깨·등","Tête, nuque, épaules et dos","头颈肩背","Голова, шея, плечи и спина"),
      desc:L("Eases desk-work tension; warm compress or hot stones.","Giảm căng cứng do ngồi nhiều; chườm ấm hoặc đá nóng.","デスクワークのこりに。温湿布またはホットストーン付き。","오래 앉아 생긴 뭉침을 따뜻한 찜질이나 핫스톤으로.","Soulage les tensions du travail de bureau ; compresse chaude ou pierres.","缓解久坐紧绷，配温敷或热石。","Снимает напряжение от сидячей работы; тёплый компресс или камни.") },
    { id:"reflex", category:"foot", image:"assets/c-foot.webp", variants:[{min:30,price:200000},{min:45,price:300000},{min:60,price:340000},{min:90,price:430000}],
      name:L("Foot Reflexology","Bấm huyệt chân","足つぼリフレクソロジー","발 반사요법","Réflexologie plantaire","足底反射疗法","Рефлексотерапия стоп"),
      desc:L("Foot cleansing, then acupressure on reflex points.","Rửa chân, rồi bấm các huyệt phản xạ.","足を清めてから反射区を指圧します。","발을 씻은 뒤 반사구를 지압합니다.","Bain de pieds puis acupression des points réflexes.","先洗脚，再按压反射区穴位。","Омовение стоп, затем точечный массаж рефлекторных зон.") },
    { id:"scrub", category:"foot", card:false, variants:[{min:60,price:490000}],
      name:L("Foot Scrub & Massage","Tẩy da chết & massage chân","フットスクラブ＆マッサージ","풋 스크럽 & 마사지","Gommage et massage des pieds","足部去角质与按摩","Скраб и массаж стоп"),
      desc:L("Exfoliation followed by a relaxing foot massage.","Tẩy tế bào chết rồi massage chân thư giãn.","角質ケアのあと、リラックスできるフットマッサージ。","각질 제거 후 편안한 발 마사지.","Exfoliation puis massage relaxant des pieds.","去角质后进行放松足部按摩。","Отшелушивание и расслабляющий массаж стоп.") },
    { id:"scrape", category:"foot", card:false, variants:[{min:60,price:450000}],
      name:L("Foot Scraping","Cạo gót chân","かかとの角質ケア","발 각질 제거","Soin des callosités","修脚去茧","Чистка стоп"),
      desc:L("Removes calluses and rough skin on heels and soles.","Loại bỏ chai sần ở gót và lòng bàn chân.","かかとや足裏の硬い角質を取り除きます。","뒤꿈치와 발바닥의 굳은살을 제거합니다.","Élimine callosités et peaux rêches des talons et plantes.","去除脚跟和脚底的老茧。","Удаление мозолей и огрубевшей кожи.") },
    { id:"p1", category:"pkg", minutes:180, price:1000000, name:L("Pure Indulgence","Pure Indulgence","ピュア・インダルジェンス","퓨어 인덜전스","Pure Indulgence","纯享套餐","Pure Indulgence"),
      desc:L("Traditional massage 60′ + relaxing hair wash 60′ + gel polish 60′","Massage truyền thống 60′ + gội đầu thư giãn 60′ + sơn gel 60′","伝統マッサージ60分＋ヘッドスパ60分＋ジェルネイル60分","전통 마사지 60분 + 헤드스파 60분 + 젤 네일 60분","Massage traditionnel 60′ + shampooing relaxant 60′ + vernis gel 60′","传统按摩 60′ + 放松洗头 60′ + 凝胶美甲 60′","Традиционный массаж 60′ + релакс-мытьё головы 60′ + гель-лак 60′") },
    { id:"p2", category:"pkg", minutes:180, price:1150000, name:L("Holistic Wellness Experience","Holistic Wellness Experience","ホリスティック・ウェルネス","홀리스틱 웰니스","Expérience bien-être globale","全方位养生体验","Holistic Wellness"),
      desc:L("Body scrub 60′ + aromatherapy 60′ + basic facial 60′","Tẩy da chết body 60′ + massage tinh dầu 60′ + chăm sóc da mặt cơ bản 60′","ボディスクラブ60分＋アロマ60分＋ベーシックフェイシャル60分","바디 스크럽 60분 + 아로마 60분 + 기본 페이셜 60분","Gommage corps 60′ + aromathérapie 60′ + soin visage 60′","身体去角质 60′ + 精油按摩 60′ + 基础面部护理 60′","Скраб тела 60′ + ароматерапия 60′ + базовый уход за лицом 60′") },
    { id:"p3", category:"pkg", minutes:180, price:1050000, name:L("Healing Touch","Healing Touch","ヒーリング・タッチ","힐링 터치","Healing Touch","疗愈之触","Healing Touch"),
      desc:L("Sunburn treatment 60′ + foot scraping 60′ + foot reflexology 60′","Phục hồi da cháy nắng 60′ + cạo gót 60′ + bấm huyệt chân 60′","日焼けケア60分＋角質ケア60分＋足つぼ60分","선번 케어 60분 + 각질 제거 60분 + 발 반사요법 60분","Soin après-soleil 60′ + soin des callosités 60′ + réflexologie 60′","晒后修复 60′ + 修脚 60′ + 足底反射 60′","Уход после солнца 60′ + чистка стоп 60′ + рефлексотерапия 60′") },
    { id:"p4", category:"pkg", minutes:165, price:1050000, name:L("Ultimate Relaxation","Ultimate Relaxation","アルティメット・リラクゼーション","얼티밋 릴랙세이션","Relaxation ultime","极致放松","Ultimate Relaxation"),
      desc:L("Herbal compress 90′ + hair wash 45′ + facial massage 30′","Chườm thảo dược 90′ + gội đầu 45′ + massage mặt 30′","ハーバルボール90分＋ヘッドスパ45分＋フェイシャルマッサージ30分","허벌 볼 90분 + 헤드스파 45분 + 얼굴 마사지 30분","Pochons d’herbes 90′ + shampooing 45′ + massage du visage 30′","草药球热敷 90′ + 洗头 45′ + 面部按摩 30′","Травяные мешочки 90′ + мытьё головы 45′ + массаж лица 30′") },
    { id:"p5", category:"pkg", minutes:165, price:1470000, perBooking:true, unit:L("for 2","cho 2 người","2名様","2인","pour 2","双人","на двоих"),
      name:L("Harmony & Balance (couple)","Harmony & Balance (cặp đôi)","ハーモニー＆バランス（カップル）","하모니 & 밸런스 (커플)","Harmonie & équilibre (duo)","和谐平衡（情侣）","Harmony & Balance (для пары)"),
      desc:L("Body massage 90′ ×2 + hair wash 45′ ×2 + mani or pedi 30′ ×2","Massage body 90′ ×2 + gội đầu 45′ ×2 + làm móng tay/chân 30′ ×2","ボディ90分×2＋ヘッドスパ45分×2＋マニキュアまたはペディキュア30分×2","바디 90분×2 + 헤드스파 45분×2 + 매니큐어 또는 페디큐어 30분×2","Massage 90′ ×2 + shampooing 45′ ×2 + manucure ou pédicure 30′ ×2","全身按摩 90′×2 + 洗头 45′×2 + 手部或足部美甲 30′×2","Массаж тела 90′ ×2 + мытьё головы 45′ ×2 + маникюр или педикюр 30′ ×2") }
  ],
  showMenuList: true,
  gallery: [
    { src:"assets/g1.webp", alt:L("Lotus pond","Hồ sen","蓮の池","연못의 연꽃","Étang de lotus","荷塘","Пруд с лотосами") },
    { src:"assets/g2.webp", alt:L("Pink lotus","Sen hồng","ピンクの蓮","분홍 연꽃","Lotus rose","粉色莲花","Розовый лотос") },
    { src:"assets/g3.webp", alt:L("Lotus in bloom","Sen nở","咲き誇る蓮","활짝 핀 연꽃","Lotus en fleur","盛开的莲花","Цветущий лотос") },
    { src:"assets/g4.webp", alt:L("Lotus on still water","Sen trên mặt nước","水面の蓮","잔잔한 물 위의 연꽃","Lotus sur l’eau calme","静水中的莲花","Лотос на воде") },
    { src:"assets/g5.webp", alt:L("Essential oils","Tinh dầu","精油","에센셜 오일","Huiles essentielles","精油","Эфирные масла") },
    { src:"assets/g6.webp", alt:L("Hot stones and flowers","Đá nóng và hoa","ホットストーンと花","핫스톤과 꽃","Pierres chaudes et fleurs","热石与鲜花","Горячие камни и цветы") }
  ],
  booking: { mode: "local", workerUrl: "", telegramBotToken: "", telegramChatId: "", maxPeople: 10, pickup: true },
  i18n: {
    en:{ services_title:"Treatments & prices", gallery_title:"The calm of the lotus" },
    vi:{ services_title:"Liệu trình & bảng giá", gallery_title:"Tĩnh lặng như hoa sen" },
    ja:{ services_title:"メニューと料金", gallery_title:"蓮のような静けさ" },
    ko:{ services_title:"트리트먼트 & 가격", gallery_title:"연꽃처럼 고요하게" },
    fr:{ services_title:"Soins et tarifs", gallery_title:"Le calme du lotus" },
    zh:{ services_title:"护理项目与价格", gallery_title:"如莲般宁静" },
    ru:{ services_title:"Процедуры и цены", gallery_title:"Спокойствие лотоса" }
  },
  designer: { zalo: { url:"https://zalo.me/0337031198", label:"0337 031 198", qr:"designer-zalo.png" } },
  publicUrl: "https://huydoan06-star.github.io/demo-phu-quoc/lotus-spa/"
};
})();
